### PR TITLE
test: register the unittest module

### LINKED ISSUE #4757: MTE tests are broken after gestalt v7 migration
Currently the module integration tests using Module Testing Environment (MTE) are all broken. 

Locally, they fail with a `VerifyException` as the testing environment is unable to find a module for a sepcific component. As far as I can observe, this is not always the same component, but the stacktrace looks quite similar every time.

```stacktrace
com.google.common.base.VerifyException: Could not find module for MappedType class org.terasology.unittest.stubs.MappedTypeComponent
	at com.google.common.base.Verify.verify(Verify.java:124)
	at com.google.common.base.Verify.verifyNotNull(Verify.java:500)
	at org.terasology.engine.core.bootstrap.EnvironmentSwitchHandler.registerComponents(EnvironmentSwitchHandler.java:197)
	at org.terasology.engine.core.bootstrap.EnvironmentSwitchHandler.handleSwitchToGameEnvironment(EnvironmentSwitchHandler.java:107)
	at org.terasology.engine.core.TerasologyEngine.initialize(TerasologyEngine.java:227)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createEngine(ModuleTestingEnvironment.java:409)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createHeadlessEngine(ModuleTestingEnvironment.java:383)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createHost(ModuleTestingEnvironment.java:451)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.setup(ModuleTestingEnvironment.java:167)
	at org.terasology.moduletestingenvironment.MTEExtension.beforeAll(MTEExtension.java:93)
```

In CI, the tests also fail but with a different error message. For instance, in [Health build #62](http://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/H/job/Health/job/develop/62/testReport/) the tests fail with a `NoClassDefFoundError` for `PathManager`.

```
java.lang.NoClassDefFoundError: org/terasology/engine/core/paths/PathManager
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createEngine(ModuleTestingEnvironment.java:401)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createHeadlessEngine(ModuleTestingEnvironment.java:383)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.createHost(ModuleTestingEnvironment.java:451)
	at org.terasology.moduletestingenvironment.ModuleTestingEnvironment.setup(ModuleTestingEnvironment.java:167)
	at org.terasology.moduletestingenvironment.MTEExtension.beforeAll(MTEExtension.java:93)
```

### PR DESCRIPTION
**Pull request by keturn**
Fixes https://github.com/MovingBlocks/Terasology/issues/4757

Requires https://github.com/MovingBlocks/Terasology/pull/4796

### CODE REVIEW

**Review by skaldarnar — DISMISSED** [review]
Can confirm that (most) MTE integration tests are working again with this.

**Comment by skaldarnar** [comment]
In CI ([PR-55#2](https://jenkins.terasology.io/teraorg/job/Terasology/job/Modules/job/M/job/ModuleTestingEnvironment/job/PR-55/2/testReport/junit/org.terasology.moduletestingenvironment/ReuseEngineTest/initializationError/)), the test stage fails with 
```
com.google.common.base.VerifyException: Could not find module for Dummy class org.terasology.moduletestingenvironment.fixtures.DummyComponent
```

Note that this happens in the unit test stage, not the integration test stage.

**Review by skaldarnar — DISMISSED** [review]

**Comment by jdrueckert** [comment]
Three integration test failures with three different issues :eyes: 
* Gradle Test Executor failure `Caused by: java.lang.OutOfMemoryError: Java heap space`
* `testWorldProvider`: 
  ```
  java.lang.NullPointerException
	at org.terasology.engine.world.block.structure.BlockDefSupportRequired.getBlockWithOverrides(BlockDefSupportRequired.java:42)
  ```
* `testSendEvent`: `MTE Safety timeout exceeded. See setSafetyTimeoutMs() ==> expected: <true> but was: <false>`

**Comment by keturn** [comment]
Issues of reliability and resource usage I am going to assume are unrelated, unless we have evidence to the contrary. (See #49)

Null Pointer Exceptions, on the other hand, I think are definitely in scope for making sure MTE is working with gestalt-module & gestalt-asset.

**Review by skaldarnar — APPROVED** [review]

**Pull request merged**
